apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes/ingress-nginx.git
    targetRevision: helm-chart-4.0.17
    path: charts/ingress-nginx
    helm:
      parameters:
        - name: "controller.admissionWebhooks.enable"
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  ## ingress-nginx namspace の作成とデプロイを同時に行う
